services:
  app:
    build: .
    container_name: blog-backend
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev 

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
